import asyncio

from grpclib.server import Server, Stream
from grpclib.utils import graceful_exit

from text_classification_grpc import GreeterBase
# generated by protoc
from text_classification_pb2 import TextClassifyRequest, TextClassifyReply


class Greeter(GreeterBase):

    async def SayTextClassify(self, stream: Stream[TextClassifyRequest, TextClassifyReply]) -> None:
        request = await stream.recv_message()
        assert request is not None
        message = f'Hello, {request.text}!'
        a = TextClassifyReply.Scores(negative=1.3, neutral=0.4, positive=0.8)
        await stream.send_message(TextClassifyReply(label=message, scores=a))


async def main(*, host: str = '127.0.0.1', port: int = 50052) -> None:
    server = Server([Greeter()])
    # Note: graceful_exit isn't supported in Windows
    with graceful_exit([server]):
        await server.start(host, port)
        print(f'Serving on {host}:{port}')
        await server.wait_closed()


if __name__ == '__main__':
    asyncio.run(main())
