# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='text_classification.proto',
    package='TextClassify',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x19text_classification.proto\x12\x0cTextClassify\"B\n\x13TextClassifyRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\xa8\x01\n\x11TextClassifyReply\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\t\x12\x36\n\x06scores\x18\x03 \x01(\x0b\x32&.TextClassify.TextClassifyReply.Scores\x1a=\n\x06Scores\x12\x10\n\x08negative\x18\x01 \x01(\x02\x12\x0f\n\x07neutral\x18\x02 \x01(\x02\x12\x10\n\x08positive\x18\x03 \x01(\x02\x32\x62\n\x07Greeter\x12W\n\x0fSayTextClassify\x12!.TextClassify.TextClassifyRequest\x1a\x1f.TextClassify.TextClassifyReply\"\x00\x62\x06proto3'
)

_TEXTCLASSIFYREQUEST = _descriptor.Descriptor(
    name='TextClassifyRequest',
    full_name='TextClassify.TextClassifyRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='model', full_name='TextClassify.TextClassifyRequest.model', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='doc_id', full_name='TextClassify.TextClassifyRequest.doc_id', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='text', full_name='TextClassify.TextClassifyRequest.text', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=43,
    serialized_end=109,
)

_TEXTCLASSIFYREPLY_SCORES = _descriptor.Descriptor(
    name='Scores',
    full_name='TextClassify.TextClassifyReply.Scores',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='negative', full_name='TextClassify.TextClassifyReply.Scores.negative', index=0,
            number=1, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='neutral', full_name='TextClassify.TextClassifyReply.Scores.neutral', index=1,
            number=2, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='positive', full_name='TextClassify.TextClassifyReply.Scores.positive', index=2,
            number=3, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=219,
    serialized_end=280,
)

_TEXTCLASSIFYREPLY = _descriptor.Descriptor(
    name='TextClassifyReply',
    full_name='TextClassify.TextClassifyReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='label', full_name='TextClassify.TextClassifyReply.label', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='score', full_name='TextClassify.TextClassifyReply.score', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='scores', full_name='TextClassify.TextClassifyReply.scores', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_TEXTCLASSIFYREPLY_SCORES, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=112,
    serialized_end=280,
)

_TEXTCLASSIFYREPLY_SCORES.containing_type = _TEXTCLASSIFYREPLY
_TEXTCLASSIFYREPLY.fields_by_name['scores'].message_type = _TEXTCLASSIFYREPLY_SCORES
DESCRIPTOR.message_types_by_name['TextClassifyRequest'] = _TEXTCLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['TextClassifyReply'] = _TEXTCLASSIFYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextClassifyRequest = _reflection.GeneratedProtocolMessageType('TextClassifyRequest', (_message.Message,), {
    'DESCRIPTOR': _TEXTCLASSIFYREQUEST,
    '__module__': 'text_classification_pb2'
    # @@protoc_insertion_point(class_scope:TextClassify.TextClassifyRequest)
})
_sym_db.RegisterMessage(TextClassifyRequest)

TextClassifyReply = _reflection.GeneratedProtocolMessageType('TextClassifyReply', (_message.Message,), {

    'Scores': _reflection.GeneratedProtocolMessageType('Scores', (_message.Message,), {
        'DESCRIPTOR': _TEXTCLASSIFYREPLY_SCORES,
        '__module__': 'text_classification_pb2'
        # @@protoc_insertion_point(class_scope:TextClassify.TextClassifyReply.Scores)
    })
    ,
    'DESCRIPTOR': _TEXTCLASSIFYREPLY,
    '__module__': 'text_classification_pb2'
    # @@protoc_insertion_point(class_scope:TextClassify.TextClassifyReply)
})
_sym_db.RegisterMessage(TextClassifyReply)
_sym_db.RegisterMessage(TextClassifyReply.Scores)

_GREETER = _descriptor.ServiceDescriptor(
    name='Greeter',
    full_name='TextClassify.Greeter',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=282,
    serialized_end=380,
    methods=[
        _descriptor.MethodDescriptor(
            name='SayTextClassify',
            full_name='TextClassify.Greeter.SayTextClassify',
            index=0,
            containing_service=None,
            input_type=_TEXTCLASSIFYREQUEST,
            output_type=_TEXTCLASSIFYREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
