import asyncio

from grpclib.client import Channel

# generated by protoc
from text_classification_pb2 import TextClassifyRequest
from text_classification_grpc import GreeterStub


async def main() -> None:
    async with Channel('127.0.0.1', 50052) as channel:
        greeter = GreeterStub(channel)

        reply = await greeter.SayTextClassify(TextClassifyRequest(text='天赐的声音王力宏现rap绝技《飘向北方》蝉联酷我音乐当期歌榜冠军 神仙打架大咖云集,王力宏再现rap“绝技”!4月25晚《天赐的声音》第九期节目高品质正版音源酷我音乐倾情上线,吴青峰、动力火车、品冠、阿肆、那吾克热、高进、高嘉朗悉数亮相...百度快照'))
        print(reply.label)
        print(reply.score)

if __name__ == '__main__':
    from tqdm import tqdm
    for i in tqdm(range(1000)):
        asyncio.run(main())
